/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/e2e5a319-ab11-47d5-bec4-b719d6b2ebc1 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int kelembaban;
  bool pompa;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
const int kering = 743;
const int basah = 310;


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  delay(1500); 
  pinMode(D0, OUTPUT);
  digitalWrite(D0, LOW);
  
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  int bacaanSensor = analogRead(A0);
  int persenSensor = map(bacaanSensor, basah, kering, 100, 0);
  Serial.println(persenSensor);
  kelembaban = persenSensor;
  
  delay(100);

  if(persenSensor>80){
    digitalWrite(D0, LOW);
    Serial.println("Pompa Mati");
    pompa = false;
  }

  if(persenSensor<20){
    digitalWrite(D0, HIGH);
    Serial.println("Pompa Menyala");
    pompa = true;
  }
 
  
}


/*
  Since Kelembaban is READ_WRITE variable, onKelembabanChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onKelembabanChange()  {
  // Add your code here to act upon Kelembaban change
  
}


/*
  Since LedPompa is READ_WRITE variable, onLedPompaChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedPompaChange()  {
  // Add your code here to act upon LedPompa change
  
}


/*
  Since PersenSensor is READ_WRITE variable, onPersenSensorChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPersenSensorChange()  {
  // Add your code here to act upon PersenSensor change
}



/*
  Since Pompa is READ_WRITE variable, onPompaChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPompaChange()  {
  // Add your code here to act upon Pompa change
  
}
